Lernwerkstatt/site

.vscode/settings.json, index.js, package-lock.json, package.json
Added browsersync to dev envireonment, now project automatically opens and hot reloads on changes. Merge shouldn't be a problem. 
`.vscode` files there are for a reason, since we all use VS Code I thought it'll be good if all of us have same(similar) configuration for this project. 
And below is demo:
=> Added browsersync

.vscode/settings.json, package.json, static/css/style.css, views/about.handlebars, views/blog.handlebars, views/contact.handlebars, views/courses.handlebars, views/home.handlebars, views/layouts/main.handlebars, views/learn.handlebars, views/support.handlebars, views/workshops.handlebars
1. Added eslint options to vs config
2. Two different lint-staged configurations for css and js
3. Wrapped {{{body}}} into **main** and renamed **.content** >> **main**
4. Removed all **.content**
=> removed divs in favor of main

static/css/style.css
the calendar had two scrollbars.
=> hide overflow

package-lock.json, views/layouts/main.hbs, views/partials/main/__snapshots__/footer.test.js.snap, views/partials/main/__snapshots__/header.test.js.snap, views/partials/main/footer.hbs, views/partials/main/footer.test.js, views/partials/main/header.hbs, views/partials/main/header.test.js
Moved header and footer into its own folder main and added snapshot tests
=> Header and footer tests

package-lock.json, package.json, src/controllers/home.js, src/controllers/home.test.js, src/modules/home/utilities.js, src/modules/home/utilities.test.js, src/routes/home.js, src/tests/utilities.js
Basically made refactoring of current home router, to make it dummy and created separate controller for handling api calls. Which gave me ability to test controller properly. Moved `utility` functions out of controller to make them reusable and avoid messing up.
=> Introducing home controller tests

src/routes/blogs.js
Fixed the broken blogs/create page
=> Fix blogs/create page

src/views/about.hbs, src/views/partials/about/__snapshots__/member.test.js.snap, src/views/partials/about/member.hbs, src/views/partials/main/__snapshots__/title.test.js.snap, src/views/partials/main/title.hbs
Removed jumbotron from page titles.
Fixed jumping descriptions for team members in about page.
=> Small design fixes

src/services/converter.test.js, src/utilities/addSummary.test.js, src/utilities/facebook.test.js
Removed __tests__ folders and placed *.test.js files next to the actual code instead
=> Remove __tests__ folders

src/utilities/facebook.js, src/utilities/facebook.test.js
The problem was that travis uses UTC and we use CEST :)
=> Fix stringifyDate tests to ignore the timezone

package-lock.json, package.json, src/controllers/home.js, src/views/home.hbs, src/views/partials/home/__snapshots__/card.test.js.snap, src/views/partials/home/card.hbs, static/css/style.css
=> Redesigned main page

src/controllers/home.js, src/views/partials/home/__snapshots__/card.test.js.snap, src/views/partials/home/card.hbs, static/css/style.css
=> Added badge to home cards

src/views/about.hbs, src/views/partials/about/__snapshots__/member.test.js.snap, src/views/partials/about/member.hbs
Co-authored-by: hikes101 <dan.streif@gmail.com>
=> Updated member descriptions to use modal instead of collapse

.vscode/settings.json
Reversed VS Code color theme to default
=> Reversed VS Code color theme

src/services/events.js, src/utilities/facebook.js, src/utilities/facebook.test.js, src/views/partials/home/__snapshots__/event.test.js.snap, src/views/partials/home/event.hbs, src/views/partials/home/modal.hbs
Used showdown to format text displayed in fb modals on the main page.
edit: I included showdowns simplifiedAutoLink option to recognize links automatically. It doesn't seem to recognize embedded links though and partial links like "facebook.com/dielernwerkstatt". Any ideas what to use for that?
=> Used showdown to format text displayed in fb modals on the main page

package-lock.json, package.json, src/index.js
Added new npm scripts to run browsersync only from command line
Added npm-run-all package
TODO:
BrowserSync is starting before Nodemon finishes booting up. We need
some way for it to wait for Nodemon to finish...
Co-authored-by: hikes101 <dan.streif@gmail.com>
=> Updated BrowserSync configs to fix new tabs opening on each reload

src/views/partials/contact/__snapshots__/modal.test.js.snap, src/views/partials/contact/modal.hbs, src/views/partials/home/__snapshots__/modal.test.js.snap, src/views/partials/home/modal.hbs, static/css/style.css
Set a max-height for modals to prevent modals from overflowing the screen and made the text itself scrollable.
=> Fixed height for modals

data/projects.json, package-lock.json, src/views/partials/contact/__snapshots__/modal.test.js.snap, src/views/partials/projects/__snapshots__/seminar.test.js.snap, src/views/partials/projects/seminar.hbs, src/views/partials/projects/seminar.test.js
=> Adjust Projects page

src/views/blogs.hbs, src/views/partials/blogs/single.hbs, static/css/style.css
=> Nicer blog posts 📝 

src/views/home.hbs, src/views/partials/home/__snapshots__/event.test.js.snap, src/views/partials/home/event.hbs
Let me know if you want further adjustments :hammer: 
edit: changed font color and size again
=> Adjust calendar text size

src/routes/blogs.js, src/routes/posts.js, src/services/database.js
The blogs are in the order newest to oldest and the home card shows the newest post.
=> Fixed blog sorting

src/views/contact.hbs
=> Minor fixes on contact page

src/views/partials/subscribe/mailchimp.hbs, src/views/subscribe.hbs
=> Refactor Subscibe page

src/views/partials/about/member.hbs, src/views/partials/home/modal.hbs, src/views/partials/main/header.hbs, src/views/partners.hbs, static/css/style.css
Old:
New:
- (TODO Consolidate modals to single partial?)
New:
Old:
New:
Old:
New:
=> Small updates for a better mobile experience

src/views/partials/main/footer.hbs
=> Mobile footer links are stacked

README.md, src/views/contact.hbs, src/views/error.hbs, src/views/home.hbs, src/views/layouts/main.hbs, src/views/partials/about/__snapshots__/member.test.js.snap, src/views/partials/about/member.hbs, src/views/partials/blogs/__snapshots__/create.test.js.snap, src/views/partials/blogs/__snapshots__/posts.test.js.snap, src/views/partials/blogs/create.hbs, src/views/partials/blogs/posts.hbs, src/views/partials/home/__snapshots__/event.test.js.snap, src/views/partials/home/__snapshots__/modal.test.js.snap, src/views/partials/home/card.hbs, src/views/partials/home/event.hbs, src/views/partials/home/modal.hbs, src/views/partials/main/__snapshots__/header.test.js.snap, src/views/partials/main/__snapshots__/title.test.js.snap, src/views/partials/main/header.hbs, src/views/partials/main/title.hbs, src/views/partials/partners/__snapshots__/partner.test.js.snap, src/views/partials/partners/partner.hbs, src/views/values.hbs
* Validate HTML
* Better Layout for Values page
* Fix Readme
=> Validate HTML with W3C Validator

browserSync.sh, package.json
Not sure if it works as expected or if an extra delay or timer is necessary. For me everything works normally but I also didn't have any problems before.
=> Move browserSync script to bash file

src/controllers/home.js, src/services/converter.js, src/services/events.js
We were already fetching event cover image, so I removed unnecessary call.
=> Removed unnecessary facebook api call

src/views/values.hbs
=> Add English content on value page

data/friends.json, src/routes/friends.js, src/routes/index.js, src/views/friends.hbs, src/views/partials/friends/__snapshots__/initiatives.test.js.snap, src/views/partials/friends/initiatives.hbs, src/views/partials/friends/initiatives.test.js, src/views/partials/main/__snapshots__/footer.test.js.snap, src/views/partials/main/footer.hbs
=> Create "Freunde" page

src/views/subscribe.hbs
Added the new newsletter archive. Bianca also wanted to have the last three newsletters displayed on the page.
=> Add new mailchimp archive

src/views/partials/main/__snapshots__/header.test.js.snap, src/views/partials/main/header.hbs, src/views/partials/projects/seminar.test.js
Here are more informations about the DDG search box and its parameters:
https://duckduckgo.com/search_box
https://duckduckgo.com/params
Once die-lernwerkstatt.org is live it will search this site for results
=> Redirect duckduckgo search box

src/views/partials/home/__snapshots__/modal.test.js.snap, src/views/partials/home/modal.hbs
Added noopener to calendar links as suggested by Chrome Audit.
=> Add noopener to calendar links

src/views/contact.hbs, src/views/partials/main/__snapshots__/footer.test.js.snap, src/views/partials/main/__snapshots__/header.test.js.snap, src/views/partials/main/footer.hbs, src/views/partials/main/header.hbs, src/views/partials/team/__snapshots__/member.test.js.snap, src/views/partials/team/member.hbs, src/views/support.hbs
**What**:
- add aria labels to forms and page links
**Why**:
- impove accessibility
**How**:
- `aria-label` tags added
**Checklist**:
[README](https://github.com/Lernwerkstatt/site/blob/master/README.md) N/A
=> Add aria labels

CONTRIBUTING.md, README.md
**What**:
Added badge for future new contributors.
Small prettier fixes for `.md` files.
**Why**:
To make our small open source more appealing :)
**How**:
**Checklist**:
=> Added badge for new contributors

src/views/layouts/main.hbs
**What**:
- Update Bootstrap and jQuery
**Why**:
- Security vulnerabilities in previously used versions
**How**:
**Checklist**:
[README](https://github.com/Lernwerkstatt/site/blob/master/README.md) N/A
Fixes #193
=> update bootstrap and jQuery

src/views/contact.hbs, src/views/layouts/main.hbs
Fixes #204 
Apparently unpkg didn't work. I went back to the manual updates for jQuery etc and it seems to work fine.
=> Remove unpkg

.github/PULL_REQUEST_TEMPLATE.md, README.md, static/robots.txt
**What**:
1. Remove the reference to the old website - it has no content anymore, just a message that it moved.
2. Adjust PR template to include `Fixes #` reference to the issue.
**Checklist**:
Fixes #189
=> chore: adjust markdown files

src/locales/en.json, src/views/contact.hbs, src/views/friends.hbs, src/views/home.hbs, src/views/partials/blogs/__snapshots__/posts.test.js.snap, src/views/partials/blogs/posts.hbs, src/views/partials/blogs/single.hbs, src/views/partials/contact/__snapshots__/modal.test.js.snap, src/views/partials/contact/modal.hbs, src/views/partials/friends/__snapshots__/initiatives.test.js.snap, src/views/partials/friends/initiatives.hbs, src/views/partials/home/__snapshots__/card.test.js.snap, src/views/partials/home/__snapshots__/cardModal.test.js.snap, src/views/partials/home/__snapshots__/modal.test.js.snap, src/views/partials/home/card.hbs, src/views/partials/home/cardModal.hbs, src/views/partials/home/modal.hbs, src/views/partials/main/__snapshots__/title.test.js.snap, src/views/partials/main/title.hbs, src/views/partials/team/__snapshots__/member.test.js.snap, src/views/partials/team/member.hbs, src/views/projects.hbs, src/views/values.hbs, static/css/style.css
**What**:
- change header styles
- semantically order header tags
**Why**:
- follow best practice
**Checklist**:
Fixes #171
=> change header semantics

src/views/layouts/main.hbs
**What**:
Add Google Analytics
**Why**:
To check out how our site is doing
**How**:
Add two script tags to the main layout, so that they are on every page
**Checklist**:
Fixes #210
=> Add Google Analytics

static/humans.txt
**What**:
- add names and email-addresses to `humans.txt`
**Why**:
- let people know who we are
**Checklist**:
Fixes #197
=> add names to humans.txt

src/routes/calendar.js, src/routes/index.js
**What**:
- add route for team calendar
**How**:
- /calendar redirects to intern calendar site
**Checklist**:
Fixes #215
=> Add calendar route

src/views/layouts/main.hbs
**What**:
- remove console message
**Why**:
- current message lacks content and formatting
- a nicer console message can be added later
**Checklist**:
Fixes #199
=> Remove console message

src/locales/de.json, src/locales/en.json, src/views/support.hbs
**What**:
- embedded betterplace donation form on support page
- DE and EN version available
@pheeria did André have any specific requests where to place the form?
**Checklist**:
Fixes #218
=> Add betterplace donation form

src/routes/home.js
**What**:
- use locale cookie to show Our Values card in either German or English
**How**:
- pass `req.cookies.locale` to `ourValues` function
**Checklist**:
Fixes #224
=> Translate Values card

src/locales/de.json, src/locales/en.json, src/routes/calendar.js, src/views/calendar.hbs, static/robots.txt
**What**:
- add `/calendar` to `robots.txt`
- embed team calendar as iframe
- mobile version not very user friendy but that seems to be a general problem of teamup
**Checklist**:
Fixes #219
=> iframe calendar

src/views/calendar.hbs
**What**:
- make iframe responsive for better ux
- not ideal for some very small screen sizes in portrait mode but works well besides that
**Checklist**:
=> Responsive iframe

src/views/partials/main/__snapshots__/header.test.js.snap, src/views/partials/main/header.hbs, static/css/style.css
**What**:
- fix visibility of navbar toggler icon
**Why**:
- design update apparently made the icon invisible
before: 
after: 
**Checklist**:
=> Fix navbar toggler visibility

src/index.js, src/routes/home.js, src/routes/index.js, src/routes/service.js
**What**:
Extract service endpoints, those that don't render anything, to a separate router.
**Why**:
Shorten `src/index.js`
**How**:
**Checklist**:
Fixes #230
=> Extract service routes

CODEOWNERS
**What**:
- update CODEOWNER names
**Why**:
- no more hikes101
Fixes #235
=> Update codeowner names

config/.eslintrc.json, config/jest.json, cypress.json, cypress/integration/home/footer.spec.js, cypress/integration/home/header.spec.js, package-lock.json, package.json
**What**:
Added E2E testing library
**Why**:
I want to learn cypress 😄 
To improve test coverage and increase confidence.
**Checklist**:
Fixes #247
=> Add cypress

src/views/partials/blogs/__snapshots__/create.test.js.snap, src/views/partials/blogs/create.hbs
**What**:
- Implemented simplemde as a markdown editor to make writing blog entries easier
Fixes #252
=> Implement simplemde for blog

package-lock.json, package.json, src/index.js
Enabling gzip will boost our website even more 🚀 
Fixes #241
=> Enable gzip compression

package-lock.json, package.json, src/locales/de.json, src/locales/en.json, src/routes/contact.js, src/views/contact.hbs
**What**:
- use nodemailer to send messages from contact form
- add basic verification step
Fixes #267
=> Fix contact form

cypress/integration/home/header.spec.js, cypress/integration/home/translations.spec.js
**What**:
Added tests for translations
**Why**:
Increase testing coverage
More reliable tests
**How**:
Clearing and setting cookies
**Checklist**:
Fixes #374
=> Add tests for translations

src/views/partials/main/__snapshots__/header.test.js.snap, src/views/partials/main/header.hbs
**What**:
- use [Osano](https://www.osano.com/) to manage cookies
**Why**:
- seems to be the fastest, easiest and most secure option at the moment
**How**:
- I created a free account for Die Lernwerkstatt and added the site
- this is a test run, so we can see if it works. at the moment there are still no third party cookies used on the site. I will open another pr to reactivate the pages with iframes
Fixes #368
=> use osano to manage cookie consent

src/views/layouts/main.hbs, src/views/partials/main/__snapshots__/header.test.js.snap, src/views/partials/main/header.hbs
**What**:
- the script needs to run first, I misplaced it in the previous pr
=> fix position of osano script

src/routes/calendar.js, src/routes/index.js, src/views/calendar.hbs
Remove team calendar as Bianca asked.
=> remove team calendar

src/views/partials/main/__snapshots__/footer.test.js.snap, src/views/partials/main/footer.hbs
**What**:
- meetup icon added to footer
=> Add meetup icon to footer

package-lock.json, package.json
Just updating almost every dependency to latest version.
=> Updating everything to latest

src/views/election_info.hbs
Another quick edit. Bianca wanted a link to the AGSB page in there.
=> Add link to agsb page

src/views/election_info.hbs
Just a change of the text for the download information.
=> Change download link text

package.json
**Why**:
The new husky version caused problems when using `git commit`.
**How**:
I followed the updated npm instructions on how to implement husky.
https://www.npmjs.com/package/husky
**Checklist**:
=> fix: husky error

src/index.js
**Why**:
Updating express-handlebars caused the local build to fail.
**How**:
Fixed the express-handlebars import and use in index.js.
**Checklist**:
[README](https://github.com/Lernwerkstatt/site/blob/master/README.md) N/A
=> fix: hbs is not a function error

src/locales/de.json, src/locales/en.json, src/views/projects.hbs
Adding new content to the projects page.
=> Add content for new project (Lernen fuers Leben)

cypress/e2e/home/header.cy.js, data/friends.json, src/locales/de.json, src/locales/en.json
Bianca asked for some content update. I'll see if I can fix the gallery in the next days. Pixlee does not support its instagram widget anymore but there are similar tools available.
For now I just added the podcasts to the existing category. Bianca wanted a separate one for the new episodes. Might look into it if I find the time for it.
=> Podcast update

README.md, src/routes/gallery.js, src/views/gallery.hbs
Pixlee stopped their service so I switched to LightWidget. Also free and does the same job.
There are probably better solutions out there but this seemed the fastest and easiest for now.
=> Switch gallery from Pixlee to LightWidget

src/views/gallery.hbs
Lightwidget seems to work as expected, just had to adjust the url for the widget. Let's hope they don#t discontinue their service as Pixlee did 🤞
=> Fix lightwidget import
